pipeline{
    agent {
        label 'server1'
    }
    stages{
        stage("build"){
            steps{
                echo"This is build stage" 
                sh "mvn clean package"
            }
            post{
                success{
                    archiveArtifacts artifacts : "**/target/*.war"
                }
            }
        }
        stage("test"){
            steps{
                echo"This is test stage"
            }
        }
        stage("deploy"){
            steps{
                echo "This is deploy stage"
            }
        }
    }
}