pipeline{
    agent any

    tools{
        maven "Maven 1"
    }

    environment{
        name = "Lokesh"
    }

    parameters {
     string defaultValue: 'taikonda', name: 'lname'
    }

    stages{
        stage("build"){
            steps{
                echo"This is build stage and $name ${params.lname}" 
                sh "mvn clean package"
            }
            post{
                success{
                    archiveArtifacts artifacts : "**/target/*.jar"
                }
            }
        }
        stage("test"){
            parallel{
                stage('A stage'){
                    echo"This is test A"
                }
                stage('B stage'){
                    echo"This is test B"
                }
            }
        }
        stage("deploy"){
            steps{
                echo "This is deploy stage"
            }
        }
    }
}